# Generated by Django 3.2.5 on 2021-08-20 22:01
import users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='البريد الالكترونى')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('mobile_number', models.CharField(max_length=11, verbose_name='رقم الموبايل')),
                ('another_mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='رقم بديل')),
                ('is_active', models.BooleanField(default=True, verbose_name='تفعيل الحساب')),
                ('is_staff', models.BooleanField(default=False, verbose_name='مستخدم')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='ادمين')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='توقيت التسجيل')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='توقيت اخر تعديل')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
            },
        ),
    ]
