# Generated by Django 3.2.5 on 2021-08-20 22:01

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='اسم الصنف')),
                ('slug', models.SlugField(allow_unicode=True, max_length=128, unique=True, verbose_name='عنوان الصنف')),
                ('image', models.ImageField(blank=True, null=True, upload_to=product.models.generate_category_image_path, verbose_name='صورة للصنف')),
            ],
            options={
                'verbose_name': 'صنف',
                'verbose_name_plural': 'الاصناف',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='اسم المنتج')),
                ('slug', models.SlugField(allow_unicode=True, max_length=256, unique=True, verbose_name='عنوان المنتج')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='السعر')),
                ('available', models.BooleanField(default=True, verbose_name='متاح')),
                ('overview', models.TextField(blank=True, null=True, verbose_name='شرح المنتج')),
                ('details', models.TextField(blank=True, null=True, verbose_name='وصف المنتج')),
                ('how_to_use', models.TextField(blank=True, null=True, verbose_name='كيفية الاستخدام')),
                ('video', models.URLField(blank=True, null=True, verbose_name='فيديو للمنتج')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='توقيت الاضافة')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='توقيت اخر تعديل')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category', verbose_name='اختر الصنف')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=product.models.generate_album_path, verbose_name='صور للمنتج')),
                ('is_master_scene', models.BooleanField(default=False, verbose_name='واجهة عرض')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='product.product')),
            ],
            options={
                'verbose_name': 'صورة للالبوم',
                'verbose_name_plural': 'صور الالبوم',
            },
        ),
    ]
