# Generated by Django 3.2.5 on 2021-09-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.BooleanField(default=False, verbose_name='عليه تخفيض'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_before_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='السعر قبل الخصم'),
        ),
    ]
