# Generated by Django 3.2.5 on 2021-09-23 14:52

import django.core.validators
from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210917_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='another_mobile_number',
        ),
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.generate_client_business_logo_path, verbose_name='لوجو الصفحة'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الالكترونى (اختيارى)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='facebook_link',
            field=models.URLField(blank=True, null=True, verbose_name='(اختيارى) لينك لصفحة الفيسبوك'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(regex='([0]{1}[1]{1}[0-9]{9})')], verbose_name='(اختيارى) رقم المحمول'),
        ),
        migrations.AlterField(
            model_name='client',
            name='terms_conditions',
            field=models.TextField(verbose_name='شروط واحكام استرجاع المنتج'),
        ),
    ]
