# Generated by Django 3.2.5 on 2021-09-23 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210923_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='facebook_link',
            field=models.URLField(blank=True, null=True, verbose_name='لينك لصفحة الفيسبوك (اختيارى)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(regex='([0]{1}[1]{1}[0-9]{9})')], verbose_name='رقم المحمول (اختيارى)'),
        ),
    ]
