# Generated by Django 3.2.5 on 2021-09-23 14:57

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210923_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.generate_client_business_logo_path, verbose_name='لوجو صفحة الفيسبوك او الموقع او المحل (اختيارى)'),
        ),
    ]
