# Generated by Django 3.2.5 on 2021-09-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_client_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='عمولة دكانه'),
        ),
    ]
