# Generated by Django 3.2.5 on 2021-08-20 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=128, verbose_name='الاسم بالكامل')),
                ('mobile_number', models.CharField(max_length=11, verbose_name='رقم المحمول')),
                ('another_mobile_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='الرقم البديل')),
                ('city', models.CharField(max_length=64, verbose_name='المحافظة')),
                ('address', models.CharField(max_length=512, verbose_name='العنوان بالتفصيل(المنطقة, اسم الشارع, رقم العقار , رقم الشقة)')),
                ('entered_at_taager', models.BooleanField(default=False, verbose_name='تم تسجيله على تاجر')),
                ('delivered_to_customer', models.BooleanField(default=False, verbose_name='تم استلام المنتج')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='توقيت التسجيل')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='توقيت اخر تعديل')),
            ],
            options={
                'verbose_name': 'اوردر تاجر',
                'verbose_name_plural': 'اوردرات تاجر',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='السعر')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='product.product', verbose_name='اسم المنتج')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
            },
        ),
    ]
