# Generated by Django 3.2.5 on 2021-09-11 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'اوردر', 'verbose_name_plural': 'اوردرات'},
        ),
        migrations.AlterField(
            model_name='order',
            name='another_mobile_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(regex='([0]{1}[1]{1}[0-9]{9})')], verbose_name='الرقم البديل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='entered_at_taager',
            field=models.BooleanField(default=False, verbose_name='تم تسجيله على منصة التسويق بالعمولة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='([0]{1}[1]{1}[0-9]{9})')], verbose_name='رقم المحمول'),
        ),
    ]
